apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: iiot-poc
spec:
  replicas: 1
  selector: { matchLabels: { app: mosquitto } }
  template:
    metadata:
      labels: { app: mosquitto }
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: cfg
              mountPath: /mosquitto/config
          readinessProbe:
            tcpSocket: { port: 1883 }
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: cfg
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: iiot-poc
spec:
  selector: { app: mosquitto }
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
  type: ClusterIP
