apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-postgres
  labels:
    app: zabbix-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres
  template:
    metadata:
      labels:
        app: zabbix-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbixpass
            - name: POSTGRES_DB
              value: zabbix
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
